In [ ]:
#1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [54]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
if np.all(arr):
    print('no zero elements')
else:
    print('there is a zero element at least')  

no zero elements


In [ ]:
#2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [53]:
arr=np.array([0,0,0,0,0,0,1,0,0])
if np.any(arr):
    print('there is a non-zero elemnt at least')
else:
    print('there isnot non-zero elemts') 

there is a non-zero elemnt at least


In [ ]:
#3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [81]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr2=np.array([1,2,3,4,5,6,7,8,9.17])

print(np.equal(arr1,arr2) )
print(np.allclose(arr1,arr3,atol=0.2))

[ True  True  True  True  True  True  True  True False]
True


In [ ]:
#4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [100]:
print(np.zeros(10))
print(np.ones(10))
print(np.repeat(5.0,10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#5. Write a NumPy program to create an array of the integers from 30 to70.

In [106]:
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
#6. Write a NumPy program to create a 3x3 identity matrix

In [107]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#7. Write a NumPy program to generate a random number between 0 and 1

In [120]:
print(np.random.rand())

0.8025860015554568


In [ ]:
#8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [121]:
print(np.random.rand(15))

[0.98421028 0.52783825 0.13068571 0.19673047 0.5336788  0.42481931
 0.72150882 0.07904113 0.60593775 0.99651386 0.23722624 0.67671865
 0.82869345 0.19973223 0.15980817]


In [ ]:
#9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [125]:
arr=np.arange(15,56)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [ ]:
#10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [135]:
arr = np.random.randint(0, 11, 5)
print(arr)

[6 7 4 3 7]


In [ ]:
#11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [152]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [164]:
arr = np.zeros((5, 5))
np.fill_diagonal(arr, [1, 2, 3, 4, 5])
print(arr)




[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [177]:
arr = np.zeros((5, 5))
for i in range(len(arr)):
    for j in range(len(arr)):
        if i==j:
            arr[i][j]=i+1
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
#13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [193]:
arr=np.zeros((4,4))
arr[::2,1::2]=1
arr[1::2,::2]=1
print(arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [ ]:
#14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [199]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
np.savez('my_arrays.npz', array1=arr1, array2=arr2)
loaded = np.load('my_arrays.npz')
print(loaded['array1'])
print(loaded['array2'])


[1 2 3 4]
[10 20 30 40]


In [ ]:
#15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

In [202]:
arr=np.random.rand(40)
print(arr)

[0.16508475 0.54543458 0.16661231 0.03883362 0.7175676  0.70327669
 0.46341252 0.81958041 0.09776789 0.64055665 0.71478702 0.86006025
 0.26137178 0.70163819 0.73851538 0.69562913 0.52379584 0.38952296
 0.95285067 0.04772337 0.00124604 0.71219879 0.30232131 0.9393402
 0.4750634  0.15324691 0.29299738 0.45615097 0.34387007 0.74919106
 0.8789551  0.73318108 0.84749795 0.62480376 0.84709905 0.52187895
 0.59471979 0.58782029 0.50146239 0.83869745]


In [126]:
#16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [204]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[(arr<7) & (arr>2)])

[3 4 5 6]
